apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockservice
  namespace: stocks
spec:
  selector:
    matchLabels:
      run: stockservice
  replicas: 1
  template:
    metadata:
      labels:
        run: stockservice
    spec:
      containers:
      - name: stockservice
        image: stockservice:1.0.0
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: stockservice
  namespace: stocks
  labels:
    run: stockservice
spec:
  type: NodePort 
  ports:
  - port: 80
  selector:
    run: stockservice
